services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_PASSWORD: password
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  frontend_node_modules: