# syntax=docker/dockerfile:1

FROM ruby:3.2.2-slim

WORKDIR /rails

ENV RAILS_ENV="development"
ENV BUNDLE_PATH="/usr/local/bundle"
ENV BUNDLE_WITHOUT="production"

# Build deps for native Ruby gems (e.g. pg)
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
    build-essential git libpq-dev curl && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

ENTRYPOINT ["/rails/bin/docker-entrypoint"]
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]

